
package org.tallerjava.cliente.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "NotificacionBancoServiceService", targetNamespace = "http://soap.ws.interfase.moduloComercio.tallerjava.org/", wsdlLocation = "http://localhost:8080/TallerJakartaEEPasarelaPagos/NotificacionBancoService?wsdl")
public class NotificacionBancoServiceService
    extends Service
{

    private static final URL NOTIFICACIONBANCOSERVICESERVICE_WSDL_LOCATION;
    private static final WebServiceException NOTIFICACIONBANCOSERVICESERVICE_EXCEPTION;
    private static final QName NOTIFICACIONBANCOSERVICESERVICE_QNAME = new QName("http://soap.ws.interfase.moduloComercio.tallerjava.org/", "NotificacionBancoServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TallerJakartaEEPasarelaPagos/NotificacionBancoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTIFICACIONBANCOSERVICESERVICE_WSDL_LOCATION = url;
        NOTIFICACIONBANCOSERVICESERVICE_EXCEPTION = e;
    }

    public NotificacionBancoServiceService() {
        super(__getWsdlLocation(), NOTIFICACIONBANCOSERVICESERVICE_QNAME);
    }

    public NotificacionBancoServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTIFICACIONBANCOSERVICESERVICE_QNAME, features);
    }

    public NotificacionBancoServiceService(URL wsdlLocation) {
        super(wsdlLocation, NOTIFICACIONBANCOSERVICESERVICE_QNAME);
    }

    public NotificacionBancoServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTIFICACIONBANCOSERVICESERVICE_QNAME, features);
    }

    public NotificacionBancoServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificacionBancoServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NotificacionBancoService
     */
    @WebEndpoint(name = "NotificacionBancoServicePort")
    public NotificacionBancoService getNotificacionBancoServicePort() {
        return super.getPort(new QName("http://soap.ws.interfase.moduloComercio.tallerjava.org/", "NotificacionBancoServicePort"), NotificacionBancoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificacionBancoService
     */
    @WebEndpoint(name = "NotificacionBancoServicePort")
    public NotificacionBancoService getNotificacionBancoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.ws.interfase.moduloComercio.tallerjava.org/", "NotificacionBancoServicePort"), NotificacionBancoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTIFICACIONBANCOSERVICESERVICE_EXCEPTION!= null) {
            throw NOTIFICACIONBANCOSERVICESERVICE_EXCEPTION;
        }
        return NOTIFICACIONBANCOSERVICESERVICE_WSDL_LOCATION;
    }

}
