
package org.tallerjava.cliente.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "NotificacionBancoService", targetNamespace = "http://soap.ws.interfase.moduloComercio.tallerjava.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotificacionBancoService {


    /**
     * 
     * @param codigoTransaccion
     * @param monto
     * @param numeroCuenta
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "notificarSaldoEntrante", targetNamespace = "http://soap.ws.interfase.moduloComercio.tallerjava.org/", className = "org.tallerjava.cliente.soap.NotificarSaldoEntrante")
    @ResponseWrapper(localName = "notificarSaldoEntranteResponse", targetNamespace = "http://soap.ws.interfase.moduloComercio.tallerjava.org/", className = "org.tallerjava.cliente.soap.NotificarSaldoEntranteResponse")
    public String notificarSaldoEntrante(
        @WebParam(name = "numeroCuenta", targetNamespace = "")
        String numeroCuenta,
        @WebParam(name = "monto", targetNamespace = "")
        double monto,
        @WebParam(name = "codigoTransaccion", targetNamespace = "")
        String codigoTransaccion);

}
