{
 "title": "JakartaProyect",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Reclamos_Comercio_Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"reclamos_comercio_total\")\n  |> cumulativeSum()\n  "
    }
   ]
  },
  {
   "title": "Pagos_Realizados_Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"pagos_realizados_total\")"
    }
   ]
  },
  {
   "title": "Pagos_Rechazados_Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"pagos_rechazados_total\")"
    }
   ]
  },
  {
   "title": "Pagos_Procesados_Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"pagos_procesados_total\")"
    }
   ]
  },
  {
   "title": "Transferencias_Recibidas_Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"transferencias_recibidas_total\")"
    }
   ]
  },
  {
   "title": "Depositos_Finalizados_Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"depositos_finalizados_total\")"
    }
   ]
  }
 ]
}